version: '2.39.2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    hostname: postgres
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build: .
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./mysite/nginx
    ports:
      - "80:80"
    depends_on:
      - django
    restart: unless-stopped

volumes:
  static_volume:


